---
- hosts: docker
  gather_facts: false
  become: true
  tasks:


     - name: listes images
      shell: docker ps

    - name: listes containers
      shell: docker images  

    - name: delete exist container
      shell: docker rm website -f

    - name: delete exist image
      shell: docker rmi mywebsite -f

    - name: delete exist image
      copy:
        src: /tmp/
        dest: /opt/web


    - name: build a new image
      shell: docker build -t mywebsite /opt/web/.

    - name: run a contaire from image for mywebsite
      shell: docker run -dit --name website -p 10:80 mywebsite
    

    - name: listes images
      shell: docker ps

    - name: listes containers
      shell: docker images  
